## Configuration of the site

# Meta fields
locale            : "en"
title             : "To be defined"
title_separator   : "-"
name              : "Jessica Walkenhorst"
description       : "Tbd2"
url               : "https://walkenho.github.io"
baseurl           : # the subpath of your site, e.g. "/blog"
repository        : "walkenho/walkenho.github.io"
teaser            : # fallback teaser image in /images/, .e.g. "500x300.png"
theme             : "minimal-mistakes-jekyll"
#theme             : "jekyll-theme-cayman"
